version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3005:3005'
    environment:
      NODE_ENV: 'production'
      PG_HOST: aima-postgres
      PG_PASS: "12345"
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: aima-postgres
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASS}
    ports:
      - "5431:5432"